name: .NET Core Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.100'
    
    - name: Restore dependencies
      run: dotnet restore Apptivate_UQMS.sln
    
    - name: Build
      run: dotnet build Apptivate_UQMS.sln --no-restore
    
    - name: Test
      run: dotnet test Apptivate_UQMS.sln --no-build --verbosity normal
